/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entite.Category;
import Entite.Produit;
import Entite.Rayon;
import Service.CategoryService;
import Service.ProduitService;
import Service.RayonService;
import connexion.connexion;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eve
 */
public class ListProduits extends javax.swing.JInternalFrame {

    ProduitService ps;
    DefaultTableModel model;
    CategoryService cs;
    RayonService rs;
    
    /**
     * Creates new form ListProduits
     */
    public ListProduits() {
        initComponents();
        ps=new ProduitService();
        cs=new CategoryService();
        rs=new RayonService();
        model=(DefaultTableModel) ListProducts.getModel();
        jPanel3.setSize(0,0);
        jPanel3.setVisible(false);
        jPanel1.setSize(950,641);
        jPanel1.setVisible(true);
        loadProduits();
        loadCategory();
        loadRayon();
    }
    static Category cat;
    static Rayon r;
    public void loadProduits()
    {
        model.setRowCount(0);
        for(Produit p:ps.findAll())
        {
            model.addRow(new Object[]{
                p.getId(),
                p.getImage(),
                p.getDesignation(),
                p.getCategor(),
                p.getPrixAchat(),
                p.getTva(),
                p.getQuantite(),
                p.getRayon()
            });
        }
    }
    public void loadCategory()
    {
        
        for(Category c:cs.findAll())
        {
            Catego.addItem(c);
          
        }
    }
    public void loadRayon()
    {
        
        for(Rayon r:rs.findAll())
        {
            Ray.addItem(r);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListProducts = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        Choice = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        imp = new javax.swing.JButton();
        images = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Tva = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        prixAchat = new javax.swing.JTextField();
        Ray = new javax.swing.JComboBox();
        Catego = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        design = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(950, 660));

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));

        ListProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Image", "Designation", "Categorie", "Prix Achat", "TVA", "Quantite", "Rayon"
            }
        ));
        ListProducts.setRowHeight(100);
        ListProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListProducts);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8_delete_50px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8_Edit_Property_50px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8_search_in_list_50px.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                searchPropertyChange(evt);
            }
        });

        Choice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Id", "Designation", "Categorie", "Prix", "Rayon" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(Choice, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel15))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Choice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        imp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        imp.setText("import");
        imp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Categorie");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("prix d'Achat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tva");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Rayon");

        Tva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TvaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Image");

        Ray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RayActionPerformed(evt);
            }
        });

        Catego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Designation");

        design.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8_image_30px.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8_category_30px.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8_similar_items_30px.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8_tax_30px.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8_Stack_of_Money_30px.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8_circle_around_30px.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8_edit_property_30px.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8_return_50px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tva, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ray, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(imp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prixAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(design, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Catego, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(images, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(15, 15, 15)
                        .addComponent(design, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(images, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Catego, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(prixAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(Tva, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ray, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(177, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
static int id;
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(ListProducts.getSelectedRowCount()>0)
        {
        int Response=JOptionPane.showConfirmDialog(this,"Etes-vous sur de vouloir supprimer le produit");
        if(Response==0)
            ps.delete(ps.findById(id));
        loadProduits();
        }
        else
            JOptionPane.showMessageDialog(this,"choisissez un produit");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(ListProducts.getSelectedRowCount()>0)
        {
        id=Integer.parseInt(model.getValueAt(ListProducts.getSelectedRow(),0).toString());
        design.setText(model.getValueAt(ListProducts.getSelectedRow(), 2).toString());
        Catego.setSelectedItem(cat);
        prixAchat.setText(model.getValueAt(ListProducts.getSelectedRow(),4).toString());
        Tva.setText(model.getValueAt(ListProducts.getSelectedRow(),5).toString());
        Ray.setSelectedItem((Rayon)model.getValueAt(ListProducts.getSelectedRow(),7));
        jPanel1.setSize(0,0);
        jPanel1.setVisible(false);
        jPanel3.setSize(950,641);
        jPanel3.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(this,"choisissez un produit");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void impActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impActionPerformed
        JFileChooser fchoser=new JFileChooser();
        FileNameExtensionFilter fnef=new FileNameExtensionFilter("PNG JPG JPEG","png","jpeg","jpg");
        fchoser.addChoosableFileFilter(fnef);

        int load=fchoser.showOpenDialog(null);
        if(load==fchoser.APPROVE_OPTION)
        {
            File f=fchoser.getSelectedFile();
            fname=f.getAbsolutePath();
            ImageIcon micon=new ImageIcon(fname);
            Image img=micon.getImage().getScaledInstance(100,100,Image.SCALE_SMOOTH);
            images.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_impActionPerformed

    private void TvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TvaActionPerformed

    private void CategoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoActionPerformed

    private void designActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designActionPerformed
String fname=null;
    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        
        Category categor=(Category)Catego.getSelectedItem();
        String designe=design.getText();
        Double prix=Double.parseDouble(prixAchat.getText());
        Double tv=Double.parseDouble(Tva.getText());

        Rayon r=(Rayon) Ray.getSelectedItem();

        try{
            String sql = "update produit set Designation='"+designe+"',categor=" + categor.getId() + ",prixAchat=" + prix + ",TVA="+tv+",rayon="+
             r.getId() + " where id="+id;
            Statement st = connexion.getConnection().createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this,"Produit mis a jour avec succes");
            loadProduits();
        }catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"produit non modifie");
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void RayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RayActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        jPanel3.setSize(0,0);
        jPanel3.setVisible(false);
        jPanel1.setSize(950,641);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void searchPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_searchPropertyChange
       
           
       
    }//GEN-LAST:event_searchPropertyChange

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        model.setRowCount(0);
        if(Choice.getSelectedItem()=="Categorie")
       {
           if(search.getText().isEmpty())
            {
                loadProduits();
            }
            else
           {
           for(Produit p:ps.findByCategory(search.getText()))
           {
               model.addRow(new Object[]{
                p.getId(),
                p.getImage(),
                p.getDesignation(),
                p.getCategor(),
                p.getPrixAchat(),
                p.getTva(),
                p.getQuantite(),
                p.getRayon()
            });
           }
           }
           
           }
        else if (Choice.getSelectedItem()=="Id")
        {
            if(search.getText().isEmpty())
            {
                loadProduits();
            }
            else
            {
            int d=Integer.valueOf(search.getText());
            Produit p=ps.findById(d);
            model.addRow(new Object[]{
                p.getId(),
                p.getImage(),
                p.getDesignation(),
                p.getCategor(),
                p.getPrixAchat(),
                p.getTva(),
                p.getQuantite(),
                p.getRayon()
            });
        }
        }
        else if (Choice.getSelectedItem()=="Designation")
        {
            if(search.getText().isEmpty())
            {
                loadProduits();
            }
            else
            {
            for(Produit p:ps.findByDesign(search.getText()))
            {
               model.addRow(new Object[]{
                p.getId(),
                p.getImage(),
                p.getDesignation(),
                p.getCategor(),
                p.getPrixAchat(),
                p.getTva(),
                p.getQuantite(),
                p.getRayon()
            }); 
            }
            }
        }
        else if (Choice.getSelectedItem()=="Prix")
        {
            if(search.getText().isEmpty())
            {
                loadProduits();
            }
            else
            {
            double pl=Double.valueOf(search.getText());
            for(Produit p:ps.findByPrix(pl))
            {
                model.addRow(new Object[]{
                p.getId(),
                p.getImage(),
                p.getDesignation(),
                p.getCategor(),
                p.getPrixAchat(),
                p.getTva(),
                p.getQuantite(),
                p.getRayon()
            }); 
            }
            }
        }
        else if(Choice.getSelectedItem()=="Rayon")
        {
            if(search.getText().isEmpty())
            {
                loadProduits();
            }
            else
            {
            for(Produit p:ps.findByRayon(search.getText()))
            {
                model.addRow(new Object[]{
                p.getId(),
                p.getImage(),
                p.getDesignation(),
                p.getCategor(),
                p.getPrixAchat(),
                p.getTva(),
                p.getQuantite(),
                p.getRayon()
            }); 
            }
        }
        }
        
    }//GEN-LAST:event_jLabel15MouseClicked

    private void ListProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListProductsMouseClicked
        id=Integer.parseInt(model.getValueAt(ListProducts.getSelectedRow(),0).toString());
        design.setText(model.getValueAt(ListProducts.getSelectedRow(), 2).toString());
        cat=(Category)model.getValueAt(ListProducts.getSelectedRow(),3);
        Catego.setSelectedItem((Category)model.getValueAt(ListProducts.getSelectedRow(),3));
        prixAchat.setText(model.getValueAt(ListProducts.getSelectedRow(),4).toString());
        Tva.setText(model.getValueAt(ListProducts.getSelectedRow(),5).toString());
        Ray.setSelectedItem((Rayon)model.getValueAt(ListProducts.getSelectedRow(),7));
    }//GEN-LAST:event_ListProductsMouseClicked
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Catego;
    private javax.swing.JComboBox Choice;
    private javax.swing.JTable ListProducts;
    private javax.swing.JComboBox Ray;
    private javax.swing.JTextField Tva;
    private javax.swing.JTextField design;
    private javax.swing.JLabel images;
    private javax.swing.JButton imp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField prixAchat;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
