/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entite.Demande;
import Entite.LigneDemande;
import Service.DemandeService;
import Service.LigneDemandeService;
import Service.ProduitService;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eve
 */
public class ListDemande extends javax.swing.JInternalFrame {

    LigneDemandeService lds;
    DemandeService ds;
    ProduitService ps;
    DefaultTableModel model;
    /**
     * Creates new form ListDemande
     */
    public ListDemande() {
        initComponents();
        lds=new LigneDemandeService();
        ds=new DemandeService();
        ps=new ProduitService();
        model=(DefaultTableModel) listCommandes.getModel();
        loadCommandes();
        Date1.setVisible(false);
        Date2.setVisible(false);
    }
    public void loadCommandes()
    {
        model.setRowCount(0);
        for(LigneDemande d:lds.findSpec())
        {
            model.addRow(new Object[]{
               d.getProduit().getDesignation(),
                d.getDemande().getFournisseur(),
                d.getDemande().getDate(),
                d.getQuantite()
        });
                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCommandes = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        Choice = new javax.swing.JComboBox();
        Date1 = new com.toedter.calendar.JDateChooser();
        Date2 = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));

        listCommandes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produit", "Fournisseur", "Date", "Quantite"
            }
        ));
        listCommandes.setRowHeight(100);
        jScrollPane1.setViewportView(listCommandes);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8_search_in_list_50px.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                searchPropertyChange(evt);
            }
        });

        Choice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Produit", "Fournisseur", "Date" }));
        Choice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChoiceItemStateChanged(evt);
            }
        });
        Choice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoiceActionPerformed(evt);
            }
        });
        Choice.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ChoicePropertyChange(evt);
            }
        });

        Date1.setDateFormatString("yyyy-MM-d");

        Date2.setDateFormatString("yyyy-MM-d");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(Date1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addGap(58, 58, 58)
                .addComponent(Date2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel15)
                .addGap(339, 339, 339))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(Choice, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Date2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Choice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        model.setRowCount(0);
        if(Choice.getSelectedItem()=="Date")
        {
            if(Date1.getDate()==null || Date2.getDate()==null)
            {
                loadCommandes();
            }
            else
            {
                
                for(LigneDemande f:lds.findBetweenDate(Date1.getDate(),Date2.getDate()))
                {
                    
                    model.addRow(new Object[]{
                        f.getProduit().getDesignation(),
                        f.getDemande().getFournisseur(),
                        f.getDemande().getDate(),
                        f.getQuantite()
                    });
                }
            }
        }

        
        else if (Choice.getSelectedItem()=="Fournisseur")
        {
            if(search.getText().isEmpty())
            {
                loadCommandes();
            }
            else
            {
                for(LigneDemande f:lds.findSpecial(search.getText()))
                {
                model.addRow(new Object[]{
                    f.getProduit().getDesignation(),
                        f.getDemande().getFournisseur(),
                        f.getDemande().getDate(),
                        f.getQuantite()
                });
            }
        }
        }
        
        else if (Choice.getSelectedItem()=="Produit")
        {
            if(search.getText().isEmpty())
            {
                loadCommandes();
            }
            else
            {
                for(LigneDemande f:lds.findSpecialist(search.getText()))
                {
                    model.addRow(new Object[]{
                        f.getProduit().getDesignation(),
                        f.getDemande().getFournisseur(),
                        f.getDemande().getDate(),
                        f.getQuantite()
                    });
                }
            }
        }
        
        
    }//GEN-LAST:event_jLabel15MouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_searchPropertyChange

    }//GEN-LAST:event_searchPropertyChange

    private void ChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChoiceActionPerformed

    private void ChoicePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ChoicePropertyChange
        
    }//GEN-LAST:event_ChoicePropertyChange

    private void ChoiceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChoiceItemStateChanged
        if(Choice.getSelectedItem()=="Date")
        {
            Date1.setVisible(true);
            Date2.setVisible(true);
            search.setVisible(false);
        }
        else{
            search.setVisible(true);
            Date1.setVisible(false);
            Date2.setVisible(false);
        }
    }//GEN-LAST:event_ChoiceItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Choice;
    private com.toedter.calendar.JDateChooser Date1;
    private com.toedter.calendar.JDateChooser Date2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listCommandes;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
